/* Admin panelinde alan adlarının Türkçe karşılıkları.
 * Burada olmayan bir alan, anahtar adıyla gösterilir. */

export const SECTION_LABELS = {
  brand: "Genel / Marka",
  navLinks: "Navbar Menüsü",
  welcome: "Açılış Kutusu",
  hero: "1 · Giriş (tam ekran)",
  about: "1b · COP Nedir (metin)",
  copHistory: "1c · COP Zirveleri",
  university: "2 · Üniversite Çalışmaları",
  projectsSection: "3a · Projeler Başlığı",
  projects: "3b · Projeler",
  law: "4 · Çevre Hukuku",
  campusMap: "5 · Kampüs Haritası",
  teamSection: "6a · Ekip Başlığı",
  team: "6b · Ekip Üyeleri",
  footer: "Alt Bilgi (Footer)",
};

export const SECTION_HINTS = {
  brand: "Site adı ve tarayıcı sekmesinde görünen başlık.",
  navLinks:
    "Menüdeki başlıklar ve sıraları. 'id' alanı sayfadaki bölümün kimliğidir — değiştirirsen bağlantı kopar.",
  welcome:
    "Sitenin ilk açılışında çıkan kutu. Kutuyu tekrar görmek için 'storageKey' değerini değiştir (örn. v2).",
  hero: "Tam ekran giriş: başlık, alt başlık, bilgi satırları, kayan fotoğraflar ve rakamlar.",
  about: "\"COP Nedir?\" bölümünün başlığı ve açıklama metni.",
  copHistory:
    "Yatay kaydırmalı zirve çizelgesi. 'Vurgulu' işaretlenen zirve yeşil olarak öne çıkar. 'Metin' alanı şeritte görünmez; fareyle üzerine gelince ipucu olarak çıkar.",
  university: "Üniversitenin COP31 çalışmaları: başlık, metin ve görsel.",
  projectsSection: "Projeler bölümünün üst başlığı ve giriş metni.",
  projects: "İki projenin tüm detayları, künye bilgileri ve liste maddeleri.",
  law: "Çevre hukuku yazısı, alıntı ve mevzuat listesi.",
  campusMap: "Harita bölümü. Görseli public/images/ içine atıp yolunu yaz.",
  teamSection: "Ekip bölümünün üst başlığı.",
  team: "Ekip üyeleri: isim, görev, bölüm, fotoğraf ve alıntı.",
  footer: "Alt bilgi metinleri, bağlantı kolonları ve telif satırı.",
};

export const FIELD_LABELS = {
  // genel
  short: "Kısa ad",
  name: "Ad",
  tagline: "Slogan",
  documentTitle: "Tarayıcı sekme başlığı",
  logoCop31: "COP31 logosu (yol)",
  logoUniversity: "Üniversite logosu (yol)",
  id: "Bölüm kimliği (id)",
  label: "Etiket / Başlık",
  title: "Başlık",
  subtitle: "Alt başlık",
  info: "Bilgi satırları",
  icon: "Simge (pin / calendar / boş)",
  eyebrow: "Üst etiket",
  lead: "Giriş metni",
  text: "Metin",
  body: "Metin",
  summary: "Özet",
  description: "Açıklama",
  href: "Bağlantı adresi",
  value: "Değer",
  suffix: "Sonek",
  note: "Açıklama",
  tone: "Renk (green / blue / soft)",
  number: "Numara",
  badge: "Rozet",
  caption: "Alt yazı",
  phase: "Faz",
  date: "Tarih",
  code: "COP numarası",
  year: "Yıl",
  city: "Şehir / Ülke",
  highlight: "Vurgulu göster",
  items: "Zirveler",
  scrollHint: "Kaydırma ipucu",
  role: "Görev",
  meta: "Bölüm / Fakülte",
  quote: "Alıntı",
  photo: "Fotoğraf yolu",
  image: "Görsel yolu",
  mapImage: "Harita görseli yolu",
  imageCaption: "Görsel alt yazısı",
  placeholderText: "Yer tutucu yazısı",
  placeholderHint: "Yer tutucu ipucu",
  author: "Yazar",
  readingTime: "Okuma süresi",
  pullQuote: "Öne çıkan alıntı",
  paragraphs: "Paragraflar",
  references: "Mevzuat listesi",
  referencesTitle: "Mevzuat kutusu başlığı",
  legend: "Harita açıklaması",
  copyright: "Telif satırı",
  columns: "Kolonlar",
  links: "Bağlantılar",
  bullets: "Maddeler",
  bulletsTitle: "Kapsam paneli başlığı",
  facts: "Künye bilgileri",
  themes: "Liste maddeleri",
  themesTitle: "Açılır panel başlığı",
  slides: "Kayan fotoğraflar",
  slideDurationMs: "Slayt süresi (ms)",
  stats: "Rakamlar",
  titleLines: "Başlık satırları",
  storageKey: "Hatırlama anahtarı",
  titleAccent: "Başlık (renkli kısım)",
  titleRest: "Başlık (devamı)",
  thanks: "Teşekkür satırı",
  button: "Buton yazısı",
};

/** Çok satırlı girilmesi gereken alanlar. */
export const LONG_FIELDS = new Set([
  "body",
  "text",
  "lead",
  "summary",
  "description",
  "quote",
  "pullQuote",
  "paragraphs",
]);

export const fieldLabel = (key) => FIELD_LABELS[key] || key;
